# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1504100971);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1504100611);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1504100851);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1504100731);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/root/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1504100604891");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1504102483891");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1504100520314");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1504104120314");
user_pref("browser.search.countryCode", "MX");
user_pref("browser.search.region", "MX");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1504100492");
user_pref("browser.slowStartup.averageTime", 3592);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20170307221322");
user_pref("browser.startup.homepage_override.mstone", "45.8.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1504186890821");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1504100552253");
user_pref("datareporting.policy.firstRunTime", "1504100490821");
user_pref("datareporting.sessions.current.activeTicks", 38);
user_pref("datareporting.sessions.current.firstPaint", 3416);
user_pref("datareporting.sessions.current.main", 569);
user_pref("datareporting.sessions.current.sessionRestored", 3604);
user_pref("datareporting.sessions.current.startTime", "1504100488625");
user_pref("datareporting.sessions.current.totalTime", 392);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.8.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1504101019);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.8.0");
user_pref("extensions.lastPlatformVersion", "45.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1488924802000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.8.0\",\"st\":1488924802000}}}");
user_pref("gecko.buildID", "20170307221322");
user_pref("gecko.mstone", "45.8.0");
user_pref("idle.lastDailyNotification", 1504101054);
user_pref("media.gmp-manager.buildID", "20170307221322");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1504100489);
user_pref("toolkit.telemetry.cachedClientID", "2053699e-1c53-4520-a9b1-4af99381d386");
user_pref("toolkit.telemetry.previousBuildID", "20170307221322");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
